# Generated by Django 2.2.1 on 2019-07-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionyperfeccionamiento',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluacionyperfeccionamiento',
            name='docentes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajo.DOCENTE'),
        ),
    ]
