# Generated by Django 2.2.1 on 2019-07-15 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legajo', '0002_auto_20190715_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cargo',
            name='docente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='legajo.DOCENTE'),
        ),
    ]
