# Generated by Django 2.2.1 on 2019-08-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajo', '0003_auto_20190715_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='DOC_APE',
        ),
        migrations.AddField(
            model_name='docente',
            name='DOC_APE_MATER',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='docente',
            name='DOC_APE_PATER',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='CUR_NOMBRE',
            field=models.CharField(max_length=60, verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='DOC_CELU',
            field=models.IntegerField(unique=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='experienciadocente',
            name='EXD_FECHA_FIN',
            field=models.DateField(verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='EXL_FECHA_FIN',
            field=models.DateField(verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='grupoinvestigacion',
            name='GI_FECHA_FIN',
            field=models.DateField(verbose_name='Fecha de Fin'),
        ),
    ]
